// ASL Gloss Converter
// Converts English sentences to ASL gloss order with proper grammar rules

// ASL Grammar Rules Applied:
// 1. Topic-Comment structure: Object often comes first ("I like cookies" -> "COOKIES I LIKE")
// 2. Time indicators at beginning ("Yesterday I went" -> "YESTERDAY I GO")
// 3. No articles (a, an, the)
// 4. No linking verbs in simple statements (am, is, are, was, were)
// 5. Adjectives can follow nouns
// 6. Questions marked by facial expression, word order often similar

// Common words that should be removed (not signed in ASL)
const SKIP_WORDS = new Set([
    'a', 'an', 'the', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'do', 'does', 'did', 'have', 'has', 'had', 'having',
    'to', 'of', 'for', 'at', 'by', 'with', 'about', 'into', 'through',
    'just', 'very', 'really', 'so', 'too', 'also'
]);

// Time indicators (should be moved to beginning)
const TIME_WORDS = new Set([
    'yesterday', 'today', 'tomorrow', 'now', 'later', 'soon', 'already',
    'before', 'after', 'always', 'never', 'sometimes', 'often', 'usually',
    'morning', 'afternoon', 'evening', 'night', 'week', 'month', 'year'
]);

// Word mappings for tense normalization and synonyms
const WORD_MAP: { [key: string]: string } = {
    // Tense normalization (ASL uses base form + time indicators)
    'went': 'GO',
    'going': 'GO',
    'goes': 'GO',
    'gone': 'GO',
    'came': 'COME',
    'coming': 'COME',
    'comes': 'COME',
    'ate': 'EAT',
    'eating': 'EAT',
    'eats': 'EAT',
    'eaten': 'EAT',
    'saw': 'SEE',
    'seeing': 'SEE',
    'sees': 'SEE',
    'seen': 'SEE',
    'said': 'SAY',
    'saying': 'SAY',
    'says': 'SAY',
    'told': 'TELL',
    'telling': 'TELL',
    'tells': 'TELL',
    'made': 'MAKE',
    'making': 'MAKE',
    'makes': 'MAKE',
    'took': 'TAKE',
    'taking': 'TAKE',
    'takes': 'TAKE',
    'taken': 'TAKE',
    'got': 'GET',
    'getting': 'GET',
    'gets': 'GET',
    'gave': 'GIVE',
    'giving': 'GIVE',
    'gives': 'GIVE',
    'given': 'GIVE',
    'thought': 'THINK',
    'thinking': 'THINK',
    'thinks': 'THINK',
    'knew': 'KNOW',
    'knowing': 'KNOW',
    'knows': 'KNOW',
    'known': 'KNOW',
    'felt': 'FEEL',
    'feeling': 'FEEL',
    'feels': 'FEEL',
    'ran': 'RUN',
    'running': 'RUN',
    'runs': 'RUN',
    'walked': 'WALK',
    'walking': 'WALK',
    'walks': 'WALK',
    'talked': 'TALK',
    'talking': 'TALK',
    'talks': 'TALK',
    'worked': 'WORK',
    'working': 'WORK',
    'works': 'WORK',
    'played': 'PLAY',
    'playing': 'PLAY',
    'plays': 'PLAY',
    'wanted': 'WANT',
    'wanting': 'WANT',
    'wants': 'WANT',
    'needed': 'NEED',
    'needing': 'NEED',
    'needs': 'NEED',
    'liked': 'LIKE',
    'liking': 'LIKE',
    'likes': 'LIKE',
    'loved': 'LOVE',
    'loving': 'LOVE',
    'loves': 'LOVE',
    'helped': 'HELP',
    'helping': 'HELP',
    'helps': 'HELP',
    'started': 'START',
    'starting': 'START',
    'starts': 'START',
    'stopped': 'STOP',
    'stopping': 'STOP',
    'stops': 'STOP',
    'tried': 'TRY',
    'trying': 'TRY',
    'tries': 'TRY',
    'used': 'USE',
    'using': 'USE',
    'uses': 'USE',
    'found': 'FIND',
    'finding': 'FIND',
    'finds': 'FIND',
    'left': 'LEAVE',
    'leaving': 'LEAVE',
    'leaves': 'LEAVE',
    'called': 'CALL',
    'calling': 'CALL',
    'calls': 'CALL',
    'asked': 'ASK',
    'asking': 'ASK',
    'asks': 'ASK',
    'waited': 'WAIT',
    'waiting': 'WAIT',
    'waits': 'WAIT',
    'bought': 'BUY',
    'buying': 'BUY',
    'buys': 'BUY',
    'sold': 'SELL',
    'selling': 'SELL',
    'sells': 'SELL',
    'sat': 'SIT',
    'sitting': 'SIT',
    'sits': 'SIT',
    'stood': 'STAND',
    'standing': 'STAND',
    'stands': 'STAND',
    'wrote': 'WRITE',
    'writing': 'WRITE',
    'writes': 'WRITE',
    'written': 'WRITE',
    'read': 'READ',
    'reading': 'READ',
    'reads': 'READ',
    'learned': 'LEARN',
    'learning': 'LEARN',
    'learns': 'LEARN',
    'taught': 'TEACH',
    'teaching': 'TEACH',
    'teaches': 'TEACH',
    'met': 'MEET',
    'meeting': 'MEET',
    'meets': 'MEET',
    'drove': 'DRIVE',
    'driving': 'DRIVE',
    'drives': 'DRIVE',
    'driven': 'DRIVE',
    'slept': 'SLEEP',
    'sleeping': 'SLEEP',
    'sleeps': 'SLEEP',
    'woke': 'WAKE',
    'waking': 'WAKE',
    'wakes': 'WAKE',
    'wore': 'WEAR',
    'wearing': 'WEAR',
    'wears': 'WEAR',
    'worn': 'WEAR',
    'brought': 'BRING',
    'bringing': 'BRING',
    'brings': 'BRING',
    'sent': 'SEND',
    'sending': 'SEND',
    'sends': 'SEND',
    'built': 'BUILD',
    'building': 'BUILD',
    'builds': 'BUILD',
    'broke': 'BREAK',
    'breaking': 'BREAK',
    'breaks': 'BREAK',
    'broken': 'BREAK',
    'opened': 'OPEN',
    'opening': 'OPEN',
    'opens': 'OPEN',
    'closed': 'CLOSE',
    'closing': 'CLOSE',
    'closes': 'CLOSE',
    'finished': 'FINISH',
    'finishing': 'FINISH',
    'finishes': 'FINISH',
    'began': 'BEGIN',
    'beginning': 'BEGIN',
    'begins': 'BEGIN',
    'begun': 'BEGIN',
    'moved': 'MOVE',
    'moving': 'MOVE',
    'moves': 'MOVE',
    'lived': 'LIVE',
    'living': 'LIVE',
    'lives': 'LIVE',
    'died': 'DIE',
    'dying': 'DIE',
    'dies': 'DIE',
    'won': 'WIN',
    'winning': 'WIN',
    'wins': 'WIN',
    'lost': 'LOSE',
    'losing': 'LOSE',
    'loses': 'LOSE',
    'paid': 'PAY',
    'paying': 'PAY',
    'pays': 'PAY',
    'spent': 'SPEND',
    'spending': 'SPEND',
    'spends': 'SPEND',
    'grew': 'GROW',
    'growing': 'GROW',
    'grows': 'GROW',
    'grown': 'GROW',
    'kept': 'KEEP',
    'keeping': 'KEEP',
    'keeps': 'KEEP',
    'let': 'LET',
    'letting': 'LET',
    'lets': 'LET',
    'put': 'PUT',
    'putting': 'PUT',
    'puts': 'PUT',
    'held': 'HOLD',
    'holding': 'HOLD',
    'holds': 'HOLD',
    'heard': 'HEAR',
    'hearing': 'HEAR',
    'hears': 'HEAR',
    'showed': 'SHOW',
    'showing': 'SHOW',
    'shows': 'SHOW',
    'shown': 'SHOW',
    'turned': 'TURN',
    'turning': 'TURN',
    'turns': 'TURN',
    'followed': 'FOLLOW',
    'following': 'FOLLOW',
    'follows': 'FOLLOW',
    'remembered': 'REMEMBER',
    'remembering': 'REMEMBER',
    'remembers': 'REMEMBER',
    'forgot': 'FORGET',
    'forgetting': 'FORGET',
    'forgets': 'FORGET',
    'forgotten': 'FORGET',
    'understood': 'UNDERSTAND',
    'understanding': 'UNDERSTAND',
    'understands': 'UNDERSTAND',
    'watched': 'WATCH',
    'watching': 'WATCH',
    'watches': 'WATCH',
    'listened': 'LISTEN',
    'listening': 'LISTEN',
    'listens': 'LISTEN',
    'touched': 'TOUCH',
    'touching': 'TOUCH',
    'touches': 'TOUCH',
    'smiled': 'SMILE',
    'smiling': 'SMILE',
    'smiles': 'SMILE',
    'laughed': 'LAUGH',
    'laughing': 'LAUGH',
    'laughs': 'LAUGH',
    'cried': 'CRY',
    'crying': 'CRY',
    'cries': 'CRY',
    'danced': 'DANCE',
    'dancing': 'DANCE',
    'dances': 'DANCE',
    'sang': 'SING',
    'singing': 'SING',
    'sings': 'SING',
    'sung': 'SING',
    'cooked': 'COOK',
    'cooking': 'COOK',
    'cooks': 'COOK',
    'cleaned': 'CLEAN',
    'cleaning': 'CLEAN',
    'cleans': 'CLEAN',
    'changed': 'CHANGE',
    'changing': 'CHANGE',
    'changes': 'CHANGE',
    'answered': 'ANSWER',
    'answering': 'ANSWER',
    'answers': 'ANSWER',
    'explained': 'EXPLAIN',
    'explaining': 'EXPLAIN',
    'explains': 'EXPLAIN',
    'decided': 'DECIDE',
    'deciding': 'DECIDE',
    'decides': 'DECIDE',
    'believed': 'BELIEVE',
    'believing': 'BELIEVE',
    'believes': 'BELIEVE',
    'hoped': 'HOPE',
    'hoping': 'HOPE',
    'hopes': 'HOPE',
    'wished': 'WISH',
    'wishing': 'WISH',
    'wishes': 'WISH',
    'arrived': 'ARRIVE',
    'arriving': 'ARRIVE',
    'arrives': 'ARRIVE',

    // Synonyms
    'hey': 'HELLO',
    'hi': 'HELLO',
    'sup': 'HELLO',
    'yo': 'HELLO',
    'howdy': 'HELLO',
    'greetings': 'HELLO',
    'okay': 'YES',
    'ok': 'YES',
    'yeah': 'YES',
    'yep': 'YES',
    'yup': 'YES',
    'sure': 'YES',
    'alright': 'YES',
    'nope': 'NO',
    'nah': 'NO',
    'thanks': 'THANK',
    'thx': 'THANK',
    'ty': 'THANK',
    'bye': 'GOODBYE',
    'goodbye': 'GOODBYE',
    'cya': 'GOODBYE',
    'later': 'GOODBYE',
    'myself': 'MY',
    'me': 'I',
    'im': 'I',
    "i'm": 'I',
    'ive': 'I',
    "i've": 'I',
    'youre': 'YOU',
    "you're": 'YOU',
    'your': 'YOU',
    'youve': 'YOU',
    "you've": 'YOU',
    'hes': 'HE',
    "he's": 'HE',
    'shes': 'SHE',
    "she's": 'SHE',
    'theyre': 'THEY',
    "they're": 'THEY',
    'were': 'WE',
    "we're": 'WE',
    'weve': 'WE',
    "we've": 'WE',
    'its': 'IT',
    "it's": 'IT',
    'dont': 'NOT',
    "don't": 'NOT',
    'doesnt': 'NOT',
    "doesn't": 'NOT',
    'didnt': 'NOT',
    "didn't": 'NOT',
    'wont': 'NOT',
    "won't": 'NOT',
    'cant': 'NOT',
    "can't": 'NOT',
    'cannot': 'NOT',
    'isnt': 'NOT',
    "isn't": 'NOT',
    'arent': 'NOT',
    "aren't": 'NOT',
    'wasnt': 'NOT',
    "wasn't": 'NOT',
    'werent': 'NOT',
    "weren't": 'NOT',
    'havent': 'NOT',
    "haven't": 'NOT',
    'hasnt': 'NOT',
    "hasn't": 'NOT',
    'hadnt': 'NOT',
    "hadn't": 'NOT',
    'wouldnt': 'NOT',
    "wouldn't": 'NOT',
    'couldnt': 'NOT',
    "couldn't": 'NOT',
    'shouldnt': 'NOT',
    "shouldn't": 'NOT',
    'mustnt': 'NOT',
    "mustn't": 'NOT',
    'ill': 'I',
    "i'll": 'I',
    'youll': 'YOU',
    "you'll": 'YOU',
    'hell': 'HE',
    "he'll": 'HE',
    'shell': 'SHE',
    "she'll": 'SHE',
    'theyll': 'THEY',
    "they'll": 'THEY',
    'well': 'WE',
    "we'll": 'WE',
    'itll': 'IT',
    "it'll": 'IT',

    // Common nouns
    'mom': 'MOTHER',
    'mommy': 'MOTHER',
    'mama': 'MOTHER',
    'dad': 'FATHER',
    'daddy': 'FATHER',
    'papa': 'FATHER',
    'kids': 'CHILDREN',
    'kid': 'CHILD',
    'children': 'CHILD',
    'guys': 'PEOPLE',
    'folks': 'PEOPLE',
    'persons': 'PEOPLE',
    'humans': 'PEOPLE',
    'human': 'PERSON',
    'automobile': 'CAR',
    'auto': 'CAR',
    'vehicle': 'CAR',
    'phone': 'TELEPHONE',
    'cellphone': 'TELEPHONE',
    'cell': 'TELEPHONE',
    'mobile': 'TELEPHONE',
    'tv': 'TELEVISION',
    'telly': 'TELEVISION',
    'pic': 'PICTURE',
    'photo': 'PICTURE',
    'photograph': 'PICTURE',
    'bucks': 'MONEY',
    'dollars': 'MONEY',
    'cash': 'MONEY',
    'h2o': 'WATER',
    'meal': 'FOOD',
    'meals': 'FOOD',
    'foods': 'FOOD',
    'puppy': 'DOG',
    'doggy': 'DOG',
    'kitty': 'CAT',
    'kitten': 'CAT',
    'residence': 'HOUSE',
    'home': 'HOUSE',
    'apartment': 'HOUSE',
    'place': 'HOUSE',
    'job': 'WORK',
    'occupation': 'WORK',
    'career': 'WORK',
    'class': 'SCHOOL',
    'college': 'SCHOOL',
    'university': 'SCHOOL',
    'buddy': 'FRIEND',
    'pal': 'FRIEND',
    'friends': 'FRIEND',
    'pals': 'FRIEND',
    'buddies': 'FRIEND'
};

// Convert English sentence to ASL gloss
export function englishToASLGloss(sentence: string): string[] {
    // 1. Clean and tokenize
    const cleaned = sentence.toLowerCase().replace(/[^a-z0-9'\s-]/g, ' ');
    const words = cleaned.split(/\s+/).filter(w => w.length > 0);

    // 2. Process words
    const timeWords: string[] = [];
    const contentWords: string[] = [];

    for (const word of words) {
        // Skip articles and linking verbs
        if (SKIP_WORDS.has(word)) continue;

        // Check if it's a time word
        if (TIME_WORDS.has(word)) {
            timeWords.push(word.toUpperCase());
            continue;
        }

        // Map word or use as-is
        const mapped = WORD_MAP[word] || word.toUpperCase();
        contentWords.push(mapped);
    }

    // 3. ASL order: TIME + CONTENT
    // Note: Full topic-comment reordering would require NLP parsing
    // For now, we keep subject-verb-object but move time to front
    const result = [...timeWords, ...contentWords];

    return result;
}

// Get list of words that have known sign animations
// Auto-generated from WORD_MAP values + explicit additions
export function getKnownSignWords(): Set<string> {
    // Start with all mapped values (verbs, nouns, etc.)
    const knownWords = new Set(Object.values(WORD_MAP));

    // Add base words that weren't in the map
    const baseWords = [
        // Greetings
        'HELLO', 'GOODBYE', 'YES', 'NO', 'THANK', 'PLEASE', 'SORRY',
        // Pronouns
        'I', 'YOU', 'HE', 'SHE', 'IT', 'WE', 'THEY', 'MY', 'YOUR', 'HIS', 'HER', 'OUR', 'THEIR',
        // Questions
        'WHAT', 'WHERE', 'WHEN', 'WHO', 'WHY', 'HOW', 'WHICH',
        // Common verbs (base forms)
        'GO', 'COME', 'EAT', 'DRINK', 'SLEEP', 'WAKE', 'WORK', 'PLAY', 'LEARN', 'TEACH',
        'KNOW', 'THINK', 'SEE', 'HEAR', 'FEEL', 'UNDERSTAND', 'REMEMBER', 'FORGET',
        'WANT', 'NEED', 'LIKE', 'LOVE', 'HATE', 'HELP', 'GIVE', 'TAKE', 'GET', 'MAKE',
        'SAY', 'TELL', 'ASK', 'ANSWER', 'TALK', 'SPEAK', 'CALL', 'WAIT', 'LOOK', 'WATCH',
        'LISTEN', 'READ', 'WRITE', 'DRAW', 'SING', 'DANCE', 'RUN', 'WALK', 'DRIVE', 'FLY',
        'SWIM', 'JUMP', 'SIT', 'STAND', 'LIE', 'FALL', 'PUSH', 'PULL', 'OPEN', 'CLOSE',
        'START', 'STOP', 'FINISH', 'BEGIN', 'END', 'TRY', 'USE', 'FIND', 'LOSE', 'WIN',
        'BUY', 'SELL', 'PAY', 'SAVE', 'SPEND', 'COST', 'SEND', 'RECEIVE', 'BRING', 'CARRY',
        'PUT', 'SET', 'LEAVE', 'STAY', 'MOVE', 'TURN', 'CHANGE', 'GROW', 'BECOME',
        'LIVE', 'DIE', 'BORN', 'MARRY', 'DIVORCE',
        // Emotions
        'HAPPY', 'SAD', 'ANGRY', 'SCARED', 'TIRED', 'SICK', 'HUNGRY', 'THIRSTY', 'EXCITED', 'BORED',
        'NERVOUS', 'PROUD', 'EMBARRASSED', 'SURPRISED', 'CONFUSED', 'WORRIED',
        // Family
        'MOTHER', 'FATHER', 'SISTER', 'BROTHER', 'SON', 'DAUGHTER', 'BABY', 'CHILD', 'PARENT',
        'GRANDMA', 'GRANDPA', 'AUNT', 'UNCLE', 'COUSIN', 'FAMILY', 'FRIEND', 'PERSON', 'PEOPLE',
        // Places
        'HOUSE', 'HOME', 'SCHOOL', 'WORK', 'STORE', 'HOSPITAL', 'CHURCH', 'PARK', 'RESTAURANT',
        'OFFICE', 'LIBRARY', 'GYM', 'BANK', 'HOTEL', 'AIRPORT', 'CITY', 'COUNTRY', 'WORLD',
        // Things
        'BOOK', 'PHONE', 'COMPUTER', 'CAR', 'BUS', 'TRAIN', 'PLANE', 'BICYCLE', 'DOOR', 'WINDOW',
        'TABLE', 'CHAIR', 'BED', 'CLOTHES', 'SHOES', 'BAG', 'KEY', 'MONEY', 'FOOD', 'WATER',
        'COFFEE', 'TEA', 'MILK', 'BREAKFAST', 'LUNCH', 'DINNER',
        // Animals
        'DOG', 'CAT', 'BIRD', 'FISH', 'HORSE', 'COW', 'PIG', 'CHICKEN', 'ANIMAL',
        // Colors
        'RED', 'BLUE', 'GREEN', 'YELLOW', 'BLACK', 'WHITE', 'ORANGE', 'PURPLE', 'PINK', 'BROWN', 'GRAY',
        // Numbers as words
        'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN',
        'HUNDRED', 'THOUSAND', 'MILLION', 'FIRST', 'SECOND', 'THIRD', 'LAST',
        // Time
        'TIME', 'DAY', 'WEEK', 'MONTH', 'YEAR', 'TODAY', 'TOMORROW', 'YESTERDAY', 'NOW', 'LATER',
        'BEFORE', 'AFTER', 'MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'HOUR', 'MINUTE', 'SECOND',
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY',
        // Adjectives
        'GOOD', 'BAD', 'BIG', 'SMALL', 'HOT', 'COLD', 'NEW', 'OLD', 'FAST', 'SLOW',
        'EASY', 'HARD', 'DIFFICULT', 'SIMPLE', 'IMPORTANT', 'BEAUTIFUL', 'UGLY', 'NICE', 'MEAN',
        'RIGHT', 'WRONG', 'TRUE', 'FALSE', 'SAME', 'DIFFERENT', 'SPECIAL', 'NORMAL', 'STRANGE',
        'QUIET', 'LOUD', 'SOFT', 'HARD', 'LIGHT', 'HEAVY', 'FULL', 'EMPTY', 'CLEAN', 'DIRTY',
        // Quantities
        'ALL', 'SOME', 'MANY', 'FEW', 'NONE', 'MORE', 'LESS', 'MOST', 'ENOUGH', 'TOO',
        // Modals
        'CAN', 'WILL', 'MUST', 'SHOULD', 'WOULD', 'COULD', 'MAY', 'MIGHT',
        // Conjunctions
        'AND', 'BUT', 'OR', 'IF', 'BECAUSE', 'SO', 'THEN', 'WHEN', 'WHILE', 'UNTIL',
        // Adverbs
        'NOT', 'AGAIN', 'ALWAYS', 'NEVER', 'SOMETIMES', 'OFTEN', 'USUALLY', 'MAYBE', 'PROBABLY',
        'REALLY', 'VERY', 'JUST', 'STILL', 'ALREADY', 'YET', 'ONLY', 'EVEN', 'ALSO', 'TOO',
        // Prepositions/Directions
        'HERE', 'THERE', 'UP', 'DOWN', 'IN', 'OUT', 'ON', 'OFF', 'OVER', 'UNDER',
        'NEAR', 'FAR', 'LEFT', 'RIGHT', 'FRONT', 'BACK', 'INSIDE', 'OUTSIDE', 'BETWEEN',
        // Other common
        'NAME', 'THING', 'IDEA', 'PROBLEM', 'QUESTION', 'ANSWER', 'REASON', 'WAY', 'PART',
        'EXAMPLE', 'FACT', 'LIFE', 'WORLD', 'STORY', 'NEWS', 'WORD', 'SENTENCE', 'LANGUAGE',
        'SIGN', 'DEAF', 'HEARING', 'COMMUNICATE', 'PRACTICE', 'LEARN', 'TEACH', 'TEST',
        // Actions
        'DONE', 'FINISH', 'COMPLETE', 'READY', 'WAIT', 'HURRY', 'RELAX'
    ];

    baseWords.forEach(w => knownWords.add(w));

    return knownWords;
}

